# Generated by Django 3.2 on 2021-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ImageField(default='blog/bamboo.jpg', upload_to=None),
        ),
    ]
