# Generated by Django 3.2 on 2021-05-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecat', '0004_productorder_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='OrderItem',
        ),
    ]
