# Generated by Django 3.2 on 2021-06-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecat', '0006_auto_20210531_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
