# Generated by Django 3.2 on 2021-06-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecat', '0007_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
