# Generated by Django 3.2 on 2021-06-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecat', '0009_auto_20210531_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='orders',
            new_name='items',
        ),
    ]
