# Generated by Django 3.2 on 2021-05-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
